name: Run iOS Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  ios-tests:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v7

      - name: Run iOS unit tests
        run: |
          xcodebuild test \
            -scheme CapacitorEmarsysPlugin \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 17' \
            -configuration Debug
